version: '3.8'

# =============================================================================
# RAG Application Docker Compose Configuration
# =============================================================================
# Profiles:
#   - default: Basic RAG application
#   - production: With nginx reverse proxy and SSL
#   - monitoring: With Prometheus and Grafana
#   - database: With PostgreSQL instead of SQLite
#   - cache: With Redis caching
#   - full: All services enabled
# =============================================================================

services:
  # =============================================================================
  # CORE APPLICATION
  # =============================================================================

  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT:-production}
    container_name: rag-app
    ports:
      - "${PORT:-8000}:8000"
    environment:
      # Core Configuration
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - DEBUG=${DEBUG:-false}
      - PORT=8000
      - HOST=0.0.0.0

      # Security
      - SESSION_SECRET=${SESSION_SECRET:-change_me_in_production}
      - CORS_ORIGINS=${CORS_ORIGINS:-["http://localhost:3000","http://localhost:8000"]}

      # Database
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./rag.db}

      # LLM Provider Configuration
      - LLM_PROVIDER=${LLM_PROVIDER:-google}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY)

      # Model Configuration
      - GOOGLE_MODEL=${GOOGLE_MODEL:-gemini-2.0-flash}

      # Document Processing
      - MAX_FILES_PER_SESSION=${MAX_FILES_PER_SESSION:-20}
      - MAX_FILE_SIZE_MB=${MAX_FILE_SIZE_MB:-10}
      - MAX_PAGES_PER_FILE=${MAX_PAGES_PER_FILE:-1000}
      - CHUNK_SIZE=${CHUNK_SIZE:-2000}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-200}

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s



